services:
  app:
    build: .
    ports:
      - "3000:5000"
    environment:
      - SECRET_KEY_FILE=/run/secrets/secrets.txt
      - PWD_FILE=/run/secrets/passwords.txt
    volumes:
      - ./input/secrets.txt:/run/secrets/secrets.txt
      - ./input/passwords.txt:/run/secrets/passwords.txt
    develop:
      watch:
        - action: sync
          path: ./src/
          target: /app/
          options:
            rsync:
              exclude:
                - .git
                - .vscode
                - __pycache__
        - action: rebuild
          path: requirements.txt
